name: 'tekartik_materializecss_asset'
version: 0.0.2
description: Materializecss for pub
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  tekartik_jquery_asset:
      git: git://github.com/alextekartik/tekartik_jquery_asset.dart